name: Node CI/CD

on:
  push:
    branches:
      - dev
      - master
      - staging
  pull_request:
    branches:
      - master
      - staging

jobs:
  build_and_unit_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar tests
        run: npm test

  dockerhub_prod_deploy:
    if: github.ref == 'refs/heads/master' #Aplicar solo en master
    needs: build_and_unit_test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Construir imagen Docker
        run: docker build -t hunglespro/node-ci-cd:prod-${{ github.sha }} .

      - name: Login a DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Subir imagen
        run: docker push hunglespro/node-ci-cd:prod-${{ github.sha }}

  dockerhub_deploy_staging:
    if: github.ref == 'refs/heads/staging' # Aplicar solo en staging
    needs: build_and_unit_test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Construir imagen Docker
        run: docker build -t hunglespro/node-ci-cd:staging-${{ github.sha }} .

      - name: Login en DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Subir imagen
        run: docker push hunglespro/node-ci-cd:staging-${{ github.sha }}

  deploy-staging:
    if: github.ref == 'refs/heads/staging' # Aplicar solo en staging
    needs: dockerhub_deploy_staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configurar kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.28.0'

      - name: Crear kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG_DATA }}" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config
        
      - name: Validar cluster
        run: kubectl get nodes
      
      - name: Actualizar imagen en manifiesto
        run: |
          kubectl set image deployment/node-ci-cd-deploy node-ci-cd=hunglespro/node-ci-cd:staging-${{ github.sha }}

      - name: Dormir para esperar despliegue
        run: sleep 60

      - name: Ver pods
        run: kubectl get pods

      - name: Ver servicios
        run: kubectl get services
